/* Reino 9: La Cima de las Ventanas — CTE y funciones de ventana */
(function (root) {
"use strict";
var A = [
{ n: 41, dif: "avanzado", tema: "SELECT", titulo: "Nombrar el resultado",
  bloque: "CTE", pide: "Usa un CTE llamado top_stock con los productos que tienen mas de 50 piezas (id, nombre, stock). Desde el CTE muestra nombre y stock ordenados por stock descendente.",
  tips: ["WITH nombre AS (SELECT ...) va antes del SELECT principal.", "El CTE se usa como si fuera una tabla mas."],
  pistas: ["Un CTE es un resultado con nombre que se declara antes de la consulta principal y se usa como si fuera una tabla.", "La sintaxis es WITH nombre AS ( ... ) seguido del SELECT principal.", "____ top_stock __ ( SELECT ... ) SELECT t.nombre, t.stock FROM top_stock t ORDER BY ...;"],
  sol: "WITH top_stock AS (\n  SELECT p.id,\n         p.nombre,\n         p.stock\n    FROM productos p\n   WHERE p.stock > 50\n)\nSELECT t.nombre,\n       t.stock\n  FROM top_stock t\n ORDER BY t.stock DESC;",
  check: { tipo: "rows", ordered: true },
  aprende: "Un CTE nombra un resultado intermedio y lo vuelve legible: la consulta se lee de arriba hacia abajo como una receta. No es mas rapido que una subconsulta, pero es infinitamente mas facil de mantener.",
  reto: "Agrega un segundo CTE que filtre los caros por categoria y consulta desde el segundo." },
{ n: 42, dif: "avanzado", tema: "SELECT", titulo: "Numerar filas",
  bloque: "Ventanas", pide: "Muestra sku, precio y un numero consecutivo (columna lugar) que ordene los productos del mas caro al mas barato. Ordena el resultado por lugar y limita a 10.",
  tips: ["ROW_NUMBER() OVER (ORDER BY ...) numera sin colapsar las filas."],
  pistas: ["Quieres numerar sin perder filas. GROUP BY colapsa; esto no.", "ROW_NUMBER() seguido de OVER con un ORDER BY adentro del parentesis.", "__________() ____ (ORDER BY p.precio DESC) AS lugar"],
  sol: "SELECT p.sku,\n       p.precio,\n       ROW_NUMBER() OVER (ORDER BY p.precio DESC) AS lugar\n  FROM productos p\n ORDER BY lugar\n LIMIT 10;",
  check: { tipo: "rows", ordered: true },
  aprende: "Una funcion de ventana calcula sobre un conjunto de filas relacionadas pero conserva cada fila. GROUP BY colapsa; OVER no. Esa es toda la diferencia.",
  reto: "Cambia ROW_NUMBER por RANK y busca donde aparecen huecos en la numeracion." },
{ n: 43, dif: "avanzado", tema: "SELECT", titulo: "Ranking por particion",
  bloque: "Ventanas", pide: "Muestra sku, categoria, precio y el lugar que ocupa cada producto DENTRO de su categoria por precio descendente (columna lugar). Ordena por categoria y lugar.",
  tips: ["PARTITION BY reinicia la numeracion en cada grupo."],
  pistas: ["La numeracion debe reiniciarse en cada categoria, no ser una sola lista global.", "Dentro del OVER, antes del ORDER BY, va la clausula que define el grupo de la ventana.", "OVER (_________ __ p.categoria ORDER BY p.precio DESC)"],
  sol: "SELECT p.sku,\n       p.categoria,\n       p.precio,\n       ROW_NUMBER() OVER (PARTITION BY p.categoria\n                              ORDER BY p.precio DESC) AS lugar\n  FROM productos p\n ORDER BY p.categoria, lugar;",
  check: { tipo: "rows", ordered: true },
  aprende: "PARTITION BY define el grupo de la ventana. Sin el, la ventana es todo el resultado; con el, cada particion arranca de cero. Es el GROUP BY de las ventanas, pero sin perder filas.",
  reto: "Agrega una segunda ventana con RANK() OVER (ORDER BY e.salario DESC) para tener el ranking global al lado del local." },
{ n: 44, dif: "avanzado", tema: "SELECT", titulo: "RANK contra DENSE_RANK",
  bloque: "Ventanas", pide: "Muestra sku, categoria y dos columnas: r con RANK() y dr con DENSE_RANK(), ambas ordenando por categoria alfabetica. Ordena por r y luego por id.",
  tips: ["Los puestos se repiten: ahi es donde RANK y DENSE_RANK se separan."],
  pistas: ["Las categorias se repiten mucho: ahi es donde las dos funciones dejan de coincidir.", "Son dos ventanas con el mismo ORDER BY, una con RANK y otra con DENSE_RANK.", "____() OVER (ORDER BY p.categoria) AS r, __________() OVER (...) AS dr"],
  sol: "SELECT p.sku,\n       p.categoria,\n       RANK()       OVER (ORDER BY p.categoria) AS r,\n       DENSE_RANK() OVER (ORDER BY p.categoria) AS dr\n  FROM productos p\n ORDER BY r, p.id;",
  check: { tipo: "rows", ordered: true },
  aprende: "RANK deja huecos despues de un empate (1, 1, 3); DENSE_RANK no (1, 1, 2); ROW_NUMBER nunca empata (1, 2, 3). Elegir mal cambia cuantos ganadores tiene un premio.",
  reto: "Agrega ROW_NUMBER() con el mismo ORDER BY y compara las tres columnas fila por fila." },
{ n: 45, dif: "avanzado", tema: "SELECT", titulo: "Total de la particion al lado",
  bloque: "Ventanas", pide: "Muestra sku, categoria, precio y el precio promedio de su categoria redondeado a dos decimales (columna prom_categoria) en cada fila. Ordena por id.",
  tips: ["SUM(...) OVER (PARTITION BY ...) suma el grupo pero conserva cada fila."],
  pistas: ["Quieres un dato del grupo al lado del dato individual, sin colapsar las filas.", "Un agregado con OVER y PARTITION BY, sin ORDER BY adentro, devuelve el valor de toda la particion.", "ROUND(___(p.precio) OVER (PARTITION BY p.__________), 2)"],
  sol: "SELECT p.sku,\n       p.categoria,\n       p.precio,\n       ROUND(AVG(p.precio) OVER (PARTITION BY p.categoria), 2) AS prom_categoria\n  FROM productos p\n ORDER BY p.id;",
  check: { tipo: "rows", ordered: true },
  aprende: "Un agregado con OVER sin ORDER BY devuelve el total de la particion en cada fila. Es la forma de poner un dato de contexto (el total del grupo) junto al dato individual sin un JOIN contra una subconsulta agrupada.",
  reto: "Agrega ROUND(100.0 * e.salario / SUM(e.salario) OVER (PARTITION BY e.sucursal_id), 1) para ver que porcentaje del gasto de su sucursal representa cada persona." },
{ n: 46, dif: "avanzado", tema: "SELECT", titulo: "Acumulado en el tiempo",
  bloque: "Ventanas", pide: "Muestra id, cantidad y el acumulado de piezas vendidas (columna acumulado) en orden de id. Limita a 12 filas.",
  tips: ["Un agregado con OVER y ORDER BY se vuelve acumulativo: suma desde la primera fila hasta la actual."],
  pistas: ["El mismo agregado cambia de significado segun lleve o no un orden dentro de la ventana.", "Con ORDER BY dentro del OVER, la suma va desde la primera fila hasta la actual: es el acumulado.", "___(v.cantidad) OVER (________ __ v.id) AS acumulado"],
  sol: "SELECT v.id,\n       v.cantidad,\n       SUM(v.cantidad) OVER (ORDER BY v.id) AS acumulado\n  FROM ventas v\n ORDER BY v.id\n LIMIT 12;",
  check: { tipo: "rows", ordered: true },
  aprende: "Con ORDER BY dentro del OVER, el agregado se calcula desde el inicio de la particion hasta la fila actual: es el acumulado. Sin ORDER BY seria el total. Un solo cambio de clausula, dos reportes distintos.",
  reto: "Agrega PARTITION BY v.empleado_id para que el acumulado se reinicie por vendedor." },
{ n: 47, dif: "avanzado", tema: "SELECT", titulo: "El mejor de cada sucursal",
  bloque: "CTE + Ventanas", pide: "Encuentra el producto mas caro de cada categoria. Usa un CTE que calcule el lugar por precio dentro de la categoria y filtra el lugar 1 afuera. Columnas: categoria, producto, precio. Ordena por precio descendente.",
  tips: ["No puedes filtrar por una ventana en el WHERE de la misma consulta: por eso el CTE.", "La ventana se calcula despues del GROUP BY, asi que puede ordenar por SUM(v.total)."],
  pistas: ["No puedes filtrar por una funcion de ventana en el WHERE de la misma consulta. Necesitas dos niveles.", "Calcula la ventana dentro de un CTE y pon el filtro en la consulta de afuera.", "WITH ranking AS ( SELECT ..., ROW_NUMBER() OVER (PARTITION BY ...) AS lugar FROM productos p ) SELECT ... FROM ranking r _____ r.lugar = _;"],
  sol: "WITH ranking AS (\n  SELECT p.categoria,\n         p.nombre AS producto,\n         p.precio,\n         ROW_NUMBER() OVER (PARTITION BY p.categoria\n                                ORDER BY p.precio DESC) AS lugar\n    FROM productos p\n)\nSELECT r.categoria,\n       r.producto,\n       r.precio\n  FROM ranking r\n WHERE r.lugar = 1\n ORDER BY r.precio DESC;",
  check: { tipo: "rows", ordered: true },
  aprende: "El patron top-N por grupo: ventana en un CTE, filtro afuera. Es la consulta que mas se pide en reportes de ventas y la que mas gente resuelve con tres subconsultas anidadas cuando bastan seis lineas.",
  reto: "Cambia lugar = 1 por lugar <= 2 y tendras el top 2 por sucursal." },
{ n: 48, dif: "avanzado", tema: "SELECT", titulo: "Porcentaje del total",
  bloque: "CTE + Ventanas", pide: "Por cada puesto muestra la nomina total (columna nomina) y el porcentaje que representa sobre la nomina general (columna pct, redondeado a un decimal). Ordena por pct descendente.",
  tips: ["El total general se obtiene con SUM(SUM(v.total)) OVER (): la ventana suma los totales ya agrupados."],
  pistas: ["Cada grupo necesita conocer el total de todos los grupos. La ventana se aplica despues de agrupar.", "SUM(SUM(columna)) OVER () suma los totales ya agregados: el interno agrupa, el externo con OVER suma esos grupos.", "ROUND(100 * SUM(e.salario) / ___(SUM(e.salario)) ____ (), 1) AS pct"],
  sol: "SELECT e.puesto,\n       SUM(e.salario) AS nomina,\n       ROUND(100 * SUM(e.salario) / SUM(SUM(e.salario)) OVER (), 1) AS pct\n  FROM empleados e\n GROUP BY e.puesto\n ORDER BY pct DESC;",
  check: { tipo: "rows", ordered: true },
  aprende: "SUM(SUM(x)) OVER () parece un trabalenguas pero es exacto: el SUM interno agrega por grupo, y el externo con OVER () suma esos grupos. Asi cada fila conoce el total general sin una subconsulta.",
  reto: "Agrega PARTITION BY dentro del OVER para obtener el porcentaje de cada producto dentro de su propia categoria." }
];
root.EJERCICIOS_AVANZADO = A;
})(typeof window !== "undefined" ? window : globalThis);
export default (typeof window !== "undefined" ? window : globalThis).EJERCICIOS_AVANZADO;