/* Reino 9: La Cima de las Ventanas — CTE y funciones de ventana */
(function (root) {
"use strict";
var A = [
{ n: 41, dif: "avanzado", tema: "SELECT", titulo: "Nombrar el resultado",
  bloque: "CTE", pide: "Usa un CTE llamado caros con los productos de precio mayor a 1000 (id, nombre, precio). Despues, desde el CTE, muestra nombre y precio ordenados por precio descendente.",
  tips: ["WITH nombre AS (SELECT ...) va antes del SELECT principal.", "El CTE se usa como si fuera una tabla mas."],
  pista: "WITH caros AS (SELECT p.id, p.nombre, p.precio FROM productos p WHERE ...) SELECT c.nombre, c.precio FROM caros c ORDER BY ...",
  sol: "WITH caros AS (\n  SELECT p.id,\n         p.nombre,\n         p.precio\n    FROM productos p\n   WHERE p.precio > 1000\n)\nSELECT c.nombre,\n       c.precio\n  FROM caros c\n ORDER BY c.precio DESC;",
  check: { tipo: "rows", ordered: true },
  aprende: "Un CTE nombra un resultado intermedio y lo vuelve legible: la consulta se lee de arriba hacia abajo como una receta. No es mas rapido que una subconsulta, pero es infinitamente mas facil de mantener.",
  reto: "Agrega un segundo CTE que filtre los caros por categoria y consulta desde el segundo." },
{ n: 42, dif: "avanzado", tema: "SELECT", titulo: "Numerar filas",
  bloque: "Ventanas", pide: "Muestra nombre, salario y un numero consecutivo (columna lugar) que ordene a los empleados del salario mas alto al mas bajo. Ordena el resultado por lugar.",
  tips: ["ROW_NUMBER() OVER (ORDER BY ...) numera sin colapsar las filas."],
  pista: "ROW_NUMBER() OVER (ORDER BY e.salario DESC) AS lugar",
  sol: "SELECT e.nombre,\n       e.salario,\n       ROW_NUMBER() OVER (ORDER BY e.salario DESC) AS lugar\n  FROM empleados e\n ORDER BY lugar;",
  check: { tipo: "rows", ordered: true },
  aprende: "Una funcion de ventana calcula sobre un conjunto de filas relacionadas pero conserva cada fila. GROUP BY colapsa; OVER no. Esa es toda la diferencia.",
  reto: "Cambia ROW_NUMBER por RANK y busca donde aparecen huecos en la numeracion." },
{ n: 43, dif: "avanzado", tema: "SELECT", titulo: "Ranking por particion",
  bloque: "Ventanas", pide: "Muestra nombre, sucursal_id, salario y el lugar que ocupa cada empleado DENTRO de su sucursal por salario descendente (columna lugar). Ordena por sucursal_id y lugar.",
  tips: ["PARTITION BY reinicia la numeracion en cada grupo."],
  pista: "ROW_NUMBER() OVER (PARTITION BY e.sucursal_id ORDER BY e.salario DESC)",
  sol: "SELECT e.nombre,\n       e.sucursal_id,\n       e.salario,\n       ROW_NUMBER() OVER (PARTITION BY e.sucursal_id\n                              ORDER BY e.salario DESC) AS lugar\n  FROM empleados e\n ORDER BY e.sucursal_id, lugar;",
  check: { tipo: "rows", ordered: true },
  aprende: "PARTITION BY define el grupo de la ventana. Sin el, la ventana es todo el resultado; con el, cada particion arranca de cero. Es el GROUP BY de las ventanas, pero sin perder filas.",
  reto: "Agrega una segunda ventana con RANK() OVER (ORDER BY e.salario DESC) para tener el ranking global al lado del local." },
{ n: 44, dif: "avanzado", tema: "SELECT", titulo: "RANK contra DENSE_RANK",
  bloque: "Ventanas", pide: "Muestra nombre, puesto, y dos columnas: r con RANK() y dr con DENSE_RANK(), ambas ordenando por puesto alfabetico. Ordena por r y luego por id.",
  tips: ["Los puestos se repiten: ahi es donde RANK y DENSE_RANK se separan."],
  pista: "RANK() OVER (ORDER BY e.puesto) AS r, DENSE_RANK() OVER (ORDER BY e.puesto) AS dr",
  sol: "SELECT e.nombre,\n       e.puesto,\n       RANK()       OVER (ORDER BY e.puesto) AS r,\n       DENSE_RANK() OVER (ORDER BY e.puesto) AS dr\n  FROM empleados e\n ORDER BY r, e.id;",
  check: { tipo: "rows", ordered: true },
  aprende: "RANK deja huecos despues de un empate (1, 1, 3); DENSE_RANK no (1, 1, 2); ROW_NUMBER nunca empata (1, 2, 3). Elegir mal cambia cuantos ganadores tiene un premio.",
  reto: "Agrega ROW_NUMBER() con el mismo ORDER BY y compara las tres columnas fila por fila." },
{ n: 45, dif: "avanzado", tema: "SELECT", titulo: "Total de la particion al lado",
  bloque: "Ventanas", pide: "Muestra nombre, salario y el total de salarios de su sucursal (columna total_sucursal) en cada fila. Ordena por id.",
  tips: ["SUM(...) OVER (PARTITION BY ...) suma el grupo pero conserva cada fila."],
  pista: "SUM(e.salario) OVER (PARTITION BY e.sucursal_id) AS total_sucursal",
  sol: "SELECT e.nombre,\n       e.salario,\n       SUM(e.salario) OVER (PARTITION BY e.sucursal_id) AS total_sucursal\n  FROM empleados e\n ORDER BY e.id;",
  check: { tipo: "rows", ordered: true },
  aprende: "Un agregado con OVER sin ORDER BY devuelve el total de la particion en cada fila. Es la forma de poner un dato de contexto (el total del grupo) junto al dato individual sin un JOIN contra una subconsulta agrupada.",
  reto: "Agrega ROUND(100.0 * e.salario / SUM(e.salario) OVER (PARTITION BY e.sucursal_id), 1) para ver que porcentaje del gasto de su sucursal representa cada persona." },
{ n: 46, dif: "avanzado", tema: "SELECT", titulo: "Acumulado en el tiempo",
  bloque: "Ventanas", pide: "Muestra id, total y el importe acumulado (columna acumulado) de las ventas en orden de id. Limita a las primeras 10.",
  tips: ["Un agregado con OVER y ORDER BY se vuelve acumulativo: suma desde la primera fila hasta la actual."],
  pista: "SUM(v.total) OVER (ORDER BY v.id) AS acumulado",
  sol: "SELECT v.id,\n       v.total,\n       SUM(v.total) OVER (ORDER BY v.id) AS acumulado\n  FROM ventas v\n ORDER BY v.id\n LIMIT 10;",
  check: { tipo: "rows", ordered: true },
  aprende: "Con ORDER BY dentro del OVER, el agregado se calcula desde el inicio de la particion hasta la fila actual: es el acumulado. Sin ORDER BY seria el total. Un solo cambio de clausula, dos reportes distintos.",
  reto: "Agrega PARTITION BY v.empleado_id para que el acumulado se reinicie por vendedor." },
{ n: 47, dif: "avanzado", tema: "SELECT", titulo: "El mejor de cada sucursal",
  bloque: "CTE + Ventanas", pide: "Encuentra al empleado que mas vendio en cada sucursal. Usa un CTE que calcule el importe por empleado y su lugar dentro de la sucursal; afuera filtra el lugar 1. Columnas: sucursal, vendedor, importe. Ordena por importe descendente.",
  tips: ["No puedes filtrar por una ventana en el WHERE de la misma consulta: por eso el CTE.", "La ventana se calcula despues del GROUP BY, asi que puede ordenar por SUM(v.total)."],
  pista: "WITH r AS (SELECT ..., ROW_NUMBER() OVER (PARTITION BY s.id ORDER BY SUM(v.total) DESC) AS lugar FROM ... GROUP BY ...) SELECT ... FROM r WHERE r.lugar = 1",
  sol: "WITH ranking AS (\n  SELECT s.nombre     AS sucursal,\n         e.nombre     AS vendedor,\n         SUM(v.total) AS importe,\n         ROW_NUMBER() OVER (PARTITION BY s.id\n                                ORDER BY SUM(v.total) DESC) AS lugar\n    FROM empleados   e\n    JOIN sucursales  s ON s.id = e.sucursal_id\n    JOIN ventas      v ON v.empleado_id = e.id\n   GROUP BY s.id, s.nombre, e.nombre\n)\nSELECT r.sucursal,\n       r.vendedor,\n       r.importe\n  FROM ranking r\n WHERE r.lugar = 1\n ORDER BY r.importe DESC;",
  check: { tipo: "rows", ordered: true },
  aprende: "El patron top-N por grupo: ventana en un CTE, filtro afuera. Es la consulta que mas se pide en reportes de ventas y la que mas gente resuelve con tres subconsultas anidadas cuando bastan seis lineas.",
  reto: "Cambia lugar = 1 por lugar <= 2 y tendras el top 2 por sucursal." },
{ n: 48, dif: "avanzado", tema: "SELECT", titulo: "Porcentaje del total",
  bloque: "CTE + Ventanas", pide: "Por cada categoria, muestra el importe vendido (columna importe) y el porcentaje que representa sobre el total general (columna pct, redondeado a un decimal). Ordena por pct descendente.",
  tips: ["El total general se obtiene con SUM(SUM(v.total)) OVER (): la ventana suma los totales ya agrupados."],
  pista: "ROUND(100 * SUM(v.total) / SUM(SUM(v.total)) OVER (), 1) AS pct",
  sol: "SELECT p.categoria,\n       SUM(v.total) AS importe,\n       ROUND(100 * SUM(v.total) / SUM(SUM(v.total)) OVER (), 1) AS pct\n  FROM productos p\n  JOIN ventas    v ON v.producto_id = p.id\n GROUP BY p.categoria\n ORDER BY pct DESC;",
  check: { tipo: "rows", ordered: true },
  aprende: "SUM(SUM(x)) OVER () parece un trabalenguas pero es exacto: el SUM interno agrega por grupo, y el externo con OVER () suma esos grupos. Asi cada fila conoce el total general sin una subconsulta.",
  reto: "Agrega PARTITION BY dentro del OVER para obtener el porcentaje de cada producto dentro de su propia categoria." }
];
root.EJERCICIOS_AVANZADO = A;
})(typeof window !== "undefined" ? window : globalThis);
export default (typeof window !== "undefined" ? window : globalThis).EJERCICIOS_AVANZADO;
